import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _iWorkFontFam = 'IworkIcon';

  static const IconData homeFill =
      IconData(0xe918, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData homeOutline =
      IconData(0xe919, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData visibilityOn =
      IconData(0xe912, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData visibilityOff =
      IconData(0xe913, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData notificationFill =
      IconData(0xe924, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData notificationOutline =
      IconData(0xe923, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData timerFill =
      IconData(0xe930, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData timerOutline =
      IconData(0xe92f, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData scheduleFill =
      IconData(0xe905, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData scheduleOutline =
      IconData(0xe904, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData tamanFill =
      IconData(0xe92e, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData tamanOutline =
      IconData(0xe92d, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData roadFill =
      IconData(0xe927, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData roadOutline =
      IconData(0xe926, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData formFill =
      IconData(0xe916, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData formOutline =
      IconData(0xe915, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData truckFill =
      IconData(0xe90b, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData truckOutline =
      IconData(0xe90a, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData mechanicFill =
      IconData(0xe920, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData mechanicOutline =
      IconData(0xe91f, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData manualFill =
      IconData(0xe91d, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData manualOutline =
      IconData(0xe91c, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData eCutiFill =
      IconData(0xe90f, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData eCutiOutline =
      IconData(0xe90e, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData ballotFill =
      IconData(0xe903, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData ballotOutline =
      IconData(0xe903, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData calendarEditFill =
      IconData(0xe907, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData calendarEditOutline =
      IconData(0xe907, fontFamily: _iWorkFontFam, fontPackage: null);

  static const IconData menu =
      IconData(0xe921, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData arrowRight =
      IconData(0xe901, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData arrowBack =
      IconData(0xe902, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData user =
      IconData(0xe931, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData logOut =
      IconData(0xe91b, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData check =
      IconData(0xe908, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData cross =
      IconData(0xe90c, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData dropdown =
      IconData(0xe90d, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData edit =
      IconData(0xe910, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData exclamation =
      IconData(0xe911, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData filter =
      IconData(0xe914, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData marker =
      IconData(0xe91e, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData navigation =
      IconData(0xe922, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData refresh =
      IconData(0xe925, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData search =
      IconData(0xe928, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData sensorAlert =
      IconData(0xe929, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData settingSlider =
      IconData(0xe92a, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData shuffle =
      IconData(0xe92b, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData history =
      IconData(0xe903, fontFamily: _iWorkFontFam, fontPackage: null);
  static const IconData bullet =
      IconData(0xe917, fontFamily: _iWorkFontFam, fontPackage: null);
}
